# Generated by Django 4.0.5 on 2022-06-21 16:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_alter_location_options_alter_location_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
